title: great art is horse shit buy tacos
email: esdrasrioos@gmail.com 
description: what matters most is how well you walk through the fire
baseurl: ""
url: "https://greatartishorseshitbuytacos.com"
github_username:  jekyll

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
