title: great art is horse shit buy tacos
email: esdrasrioos@gmail.com 
description: what matters most is how well you walk through the fire
baseurl: ""
url: greatartishorseshitbuytacos.com
url: https://greatartishorseshitbuytacos.com
github_username:  esdrasrios

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - LICENSE
  - README.md
  - vendor
  - [vendor]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
